services:
  - type: web
    name: ai-trip-planner-backend
    env: python
    buildCommand: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: gunicorn main:app --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: "3.10.0"
      - key: PORT
        value: 10000
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: GROQ_API_KEY
        sync: false  # Set this in Render dashboard
      # Add other required API keys here
    plan: free  # or 'starter' if you need more resources